### ISSUE TITLE
Include explicit GLSL to SPIRV compilation

### ISSUE THREAD

**Issue by alexander-g** [EthicalML/vulkan-kompute#107]
Currently raw GLSL source code is directly passed to `vkCreateShaderModule`. I believe this works only with the Nvidia driver as indictated by [this](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_glsl_shader.html) extension, which is deprecated without replacement. It does not work for other drivers, I have tested it with the default Intel driver on my Microsoft Surface and got a segfault. (Works fine with SPIRV). 
Additionally if the GLSL code is incorrect only a `VK_ERROR_INVALID_SHADER_NV` exception is thrown without additional information what is wrong.
Both could be fixed by including the [glslang](https://github.com/KhronosGroup/glslang) compiler.

**Comment by axsaucedo** [comment]
That is absolutely right - it has actually come up several times, and utliamtely it only works if the glslang libraries are installed in the respective machine. I don't think we would want to include this library, but I agree that potentially adding this as part of the documentation could be enough to ensure people know why there may be a segfault in place. 

To provide further detail, some issues that show this behaviour include https://github.com/EthicalML/vulkan-kompute/issues/100 and https://github.com/EthicalML/vulkan-kompute/issues/84.

**Comment by alexander-g** [comment]
Why not include it? The overhead is small and it helps a lot during development when you quickly want to change a shader, especially with python.

**Comment by axsaucedo** [comment]
@alexander-g the main reason I woudl think against it would be adding a dependency that would only be required when explicitly needed. All other dependencies are either built from source (with the submodule + cmake) installing all relevant dependencies or using static libs. Not adding it would not block people from being able to just install it themselves by following the makefile target, so it basically would be whether Kompute should take the complexity of installing it, which would seem as more maintenance overhead than benefit (vs documentation that just points people to `make install` glsl itself).

**Comment by alexander-g** [comment]
The GLSL compiler from Khronos is exactly simply a submodule that compiled to a static lib.
I will try to implement it and write a PR, then you can decide.

**Comment by axsaucedo** [comment]
Closing this issue to continue discussion on #150
