### ISSUE TITLE
Add support for VK_EXT_debug_utils labels

### ISSUE THREAD

**Issue by alexander-g** [EthicalML/vulkan-kompute#110]
I am trying to profile a `Sequence.eval()` consisting of many shader calls. Unfortunately it's not possible to see which shader took how much time, the profiler shows only the Vulkan API calls (`vkWaitForFences` as below).

![image](https://user-images.githubusercontent.com/3867427/104126405-982b4000-535c-11eb-996e-f6ea18196b11.png)

It would be great to integrate the [VK_EXT_debug_utils](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_utils.html) extension into Kompute to mark specific sections in the Sequence, so that they can be displayed individually in the profiler.

**Comment by alexander-g** [comment]
Turns out this extension is not what I want. It creates the markers during the creation of `Sequence()` and not during `eval()`.
I am experimenting with writing clock values into buffers manually from inside the shaders.

**Comment by axsaucedo** [comment]
Interesting - could you share the snippet that you have to do this? I do see what you mean that you'd like to evaluate the time taken per shader. Would it not be the same if you were to create multiple `kp::Sequence`, each with the respective shader, but all sharing the same Tensors, and then basically benchmarking each of them? In theory there wouldn't be any overhead if you were to record all commands on initialisation across each Sequence, and only the `eval` is called. Is there a reason why you want to do it in a single sequence instead?

**Comment by alexander-g** [comment]
For testing, I have simply hardcoded the following code into `OpAlgoBase::record()` right before `this->mAlgorithm->recordDispatch`

```
PFN_vkCmdInsertDebugUtilsLabelEXT pfnCmdInsertDebugUtilsLabelEXT = (PFN_vkCmdInsertDebugUtilsLabelEXT)this->mDevice->getProcAddr("vkCmdInsertDebugUtilsLabelEXT");
if(pfnCmdInsertDebugUtilsLabelEXT != nullptr){
    const VkDebugUtilsLabelEXT label0 =
    {
        VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT, // sType
        NULL,                                    // pNext
        "Banana",                           // pLabelName
        { 1.0f, 0.0f, 0.0f, 1.0f },              // color
    };
    pfnCmdInsertDebugUtilsLabelEXT( (VkCommandBuffer)(*this->mCommandBuffer.get()), &label0);
}
```
(plus extension initialization in the Manager)
But this creates the markers only once during the operation recording and not later during the `eval`s

Your methods sounds simpler, I should have come up with it by myself, I will try it.

**Comment by axsaucedo** [comment]
Oh I see, wow interesting, there's just so many useful extensions that would be worth looking at. I think having some tooling / documentation on how to do best pactices benchmarking would eb very useful.

> Your methods sounds simpler, I should have come up with it by myself, I will try it.

To be honest, the sequences/commands component is not as well documented, so I would be keen to add a benchmarking example, similar to some of the examples in the `examples/` folder. There are some there which show how to record multiple commands per sequence, and you can even see how you can use multiple queues for concurrent processing when possible to add even further speedups https://towardsdatascience.com/parallelizing-heavy-gpu-workloads-via-multi-queue-operations-50a38b15a1dc

**Comment by axsaucedo** [comment]
@alexander-g is this still required now that timestamping support has been added?

**Comment by alexander-g** [comment]
I for one don't need this anymore.
