### ISSUE TITLE
Setup automated CI testing for PRs using GitHub actions

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/vulkan-kompute#114]
Currently all PRs that have been contributed require pulling the specific branch and running the tests. It would provide much more speedy development cycles especially for contributors through automated CI builds that show on each of the PRs. 

This PR encompasses exploring setting up automated CI tests initially for C++, but also for the python tests.

**Comment by alexander-g** [comment]
I had this lying around for some time already, but not yet finished. Will take a look again.
For tests one can use [swiftshader](https://github.com/google/swiftshader) CPU implementation of Vulkan. However it does not support GLSL (*hint*hint*).

**Comment by axsaucedo** [comment]
Wow swiftshader looks awesome - interestingly enough I have been wanting to find something for quite a LONG time now, I have an open issue in the VK HPP repo which has had no movement https://github.com/KhronosGroup/Vulkan-Hpp/issues/734

Haha good point on the glsl piece! Having said that tho, I would still be keen to explore the point about just installing shaderc, as potentailly that could make sure that it's always possible to pass string shaders (without the need to first convert them into spirv explicitly with the glsl dependency).

The point on swiftshader is very interesting tho - have you had a chance to try it by any chance?

**Comment by alexander-g** [comment]
Yes it works fine. I'm already using it for CI in a private repo.

**Comment by axsaucedo** [comment]
Interesting. Do you have a snippet that you coudl share? Or is this something you think you could add to the cmake file for the tests? This would really bring a lot of value as then it would be possible to set up github actions to run the tests on every PR submitted

**Comment by alexander-g** [comment]
Here are also Swiftshader Windows binaries. However I remember I got a segfault when using Kompute Python with it. The Vulkan sample apps like vkcube.exe work fine however.
Will take a look at it sometime later again.

[vk_swiftshader.dll](https://www.dropbox.com/s/y64qrkd5qbmucws/vk_swiftshader.dll?dl=1)
[vk_swiftshader.debug.dll](https://www.dropbox.com/s/l7gnlupj2ukb56v/vk_swiftshader.debug.dll?dl=1)
