### ISSUE TITLE
Remove references to spdlog in python module

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/vulkan-kompute#122]
Since we now use the python logger via #118, there is no longer need to have references to spdlog

**Comment by alexander-g** [comment]
One issue with the python logger I've noticed is that it does not automatically format the strings as spdlog does.
E.g: `SPDLOG_DEBUG("{}", 777)` will be displayed as `"{}"`  in Python. This should be easily fixable though, because python also allows `"{}".format(777)`
