### ISSUE TITLE
Starting slack group or discord for alternative / faster version of asking questions

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/vulkan-kompute#198]
Currently we have github issues as a primary means to report issues or track features. However there are quite a few questions that come up which could be addressed more efficiently using a chat-like functionality. From an initial search to see what other communities are using / are happy with, it seems discord is gaining popularity so we can start with that and re-asses based on usage

**Comment by unexploredtest** [comment]
That'll be nice! Let me know if you needed any hands with it

**Comment by axsaucedo** [comment]
I have now created the discord server, you can join via: https://discord.gg/ywjaBH6v24

![image](https://user-images.githubusercontent.com/1447507/113313719-6d210e80-9303-11eb-85dc-742a930e2490.png)

**Comment by axsaucedo** [comment]
cc all contributors [ @alexander-g  @hpgmiskin @pH5 @nihui @0x0f0f0f @Dudecake @DonaldWhyte ] you can join the newly created discord server via  https://discord.gg/ywjaBH6v24
