### ISSUE TITLE
external  libraries

### ISSUE THREAD

**Issue by grzavala** [EthicalML/vulkan-kompute#201]
I cannot link to the project the fmt library+ias and those in the external directory.

**Comment by unexploredtest** [comment]
Have you set the option `KOMPUTE_OPT_REPO_SUBMODULE_BUILD`?
Like `cmake -Bbuild -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1 (other options)...`?

**Comment by grzavala** [comment]
I try to make my own calculation applications and I see in Kompute a potential for my developments in complex numerical models (hydraulics and hydrology).But I am not familiar with cMake I don't use it. On the other hand I recently have a working 3D Digital Terrain model in Vulkan to which I want to add computational potential.
I have cloned the Kompute repository and I have lifted the project with "Visual Studio 2019 Comunity" in Windows 10. At compile time I get this message:
---
Gravedad	Código Descripción Proyecto	Archivo Línea Estado suprimido Error CMake Error at src/CMakeLists.txt:88 (find_package):  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "fmt", but CMake did not find one.

  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed. e:\vulkan-kompute\src/CMakeLists.txt	88	
 ---

If I comment out the addition of "fmt", the directory not found error goes to the next library "glslang", etc minus the "Vulkan-Header" one. I have tried, but I don't know how to solve this problem.

**Comment by axsaucedo** [comment]
@grzavala the easiest way to address this as @unexploredtest suggests is to build with KOMPUTE_OPT_REPO_SUBMODULE_BUILD=1, this is a parameter that you have to add as part of your build configuration in visual studio

**Comment by axsaucedo** [comment]
You also need to make sure you clone the repo with the `--recursive` flag, which  ensures that all the sub-repos are cloned as well (including glslang, fmt, etc). Basically this makes it simpler as it ensures all the dependencies are packaged up together with Kompute.

**Comment by axsaucedo** [comment]
Best practice would be to change your visual studio parameters, but you can also change this on your file, specifically on this line: https://github.com/EthicalML/vulkan-kompute/blob/3aa2ca79c28aa4eb3a5101dffac3977314f439fd/CMakeLists.txt#L19

**Comment by grzavala** [comment]
The cloning of the Kompute repository is complete on my computer, I checked the directories.  I also did it several times.
I have put the suggestions of unexploredtest and axsaucedo:
1) in vulkan-kompute/src/CMakeLists.txt.
option(KOMPUTE_OPT_REPO_SUBMODULE_BUILD, "Use the submodule repos instead of external package manager" 0)
2) as compile argument option:  -KOMPUTE_OPT_OPT_REPO_SUBMODULE_BUILD=1
 
But ... same error.

**Comment by axsaucedo** [comment]
You have to use the compile option -DKOMPUTE_OPT_OPT_REPO_SUBMODULE_BUILD=1, with -D at the beginning - you can also just change the 0 to 1 on the cmakelists.txt file. Could you try that?

**Comment by grzavala** [comment]
Resolved !!! Complete compilation.
It worked by setting:-KOMPUTE_OPT_OPT_OPT_REPO_SUBMODULE_BUILD = 1 in CMakeSettings.json in Command Arguments (additional command line options passed to CMake when invoked to generate the cache). 
Did not work in Compile Command Arguments: (native build modifiers passed to CMake after --build).  Thanks!!!

**Comment by grzavala** [comment]
sorry, I misspelled above. It is: -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1

**Comment by axsaucedo** [comment]
Fantastic news - cmake can always be quite fiddly, but it does simplify complexity in the larger scale. Ok in this case I will close this issue. Please feel free to reopen or open a new one if you run into other issues.

**Comment by grzavala** [comment]
Good morning. The CMake project in Visual Studio 2019 Comunity loaded completely and did not throw errors with the addresses of the libraries with the indications provided. But for the next step, when I choose a program to run inside the structure (any *.cpp), I get errors in the #includes <kompute/Kompute.hpp>.  (error) Cannot open the source file. How can I fix this?

**Comment by axsaucedo** [comment]
@grzavala are you able to run the tests? If so, you would just need to make sure your cmake file has a similar structure to that. Alternatively you can try running one of the examples like the logistic regression as they are semi-independent, as in they import the main project, and use the kompute.hpp header

**Comment by grzavala** [comment]
I cannot run the tests. I don't know how to do it. I would need an example of how to modify or adapt CMakeLists.txt
I have tried placing subdirectories and pointing to executables but something must be missing.

**Comment by unexploredtest** [comment]
@grzavala To enable tests, you have to enable the cmake option `KOMPUTE_OPT_BUILD_TESTS`(set it to zero) just like how you enabled `KOMPUTE_OPT_REPO_SUBMODULE_BUILD` in CMakeSettings.json
