### ISSUE TITLE
SWIG syntax error - change order of keywords.

### ISSUE THREAD

**Issue by 0x0f0f0f** [EthicalML/vulkan-kompute#94]
I am generating bindings for Go using SWIG. A bit challenging for me tbh.
I do not know if it is a convention or not, but SWIG failed throwing a syntax error when parsing lines from the single header containing:
```
static unsigned const
```

I figured out that just changing the order to this, fixed the problem.
```
static const unsigned
```

Yes, this is funny, but it made SWIG accept the `Kompute.hpp` header. lol.
I'm not familiar with quom at all. I'll try opening a PR

**Comment by axsaucedo** [comment]
Oh wow, that seems like a pretty nasty bug, thanks for the heads up, I think having SWIG interoperability would be important - currently the [Python bindings](https://kompute.cc/overview/python-package.html) are built using Cython and Pybind11, but SWIG is always a common tool for these. I would be interested to learn more about your implementation, if you publish it I'd be keen to try it and link it as I do quite a lot of work in Go as well.

**Comment by 0x0f0f0f** [comment]
github.com/0x0f0f0f/kompute-go

Just tried this morning to make SWIG generate the wrapper. Works, assumes kompute is installed in /usr/local/lib . Only thing is that the types and methods are kinda messed up. I would really like to implement kompute for go. HMU by mail!

**Comment by axsaucedo** [comment]
Thank you again @0x0f0f0f ! I will close this issue for now, but I would be very keen to explore the kompute-go piece, seems quite interesting!
